### ISSUE TITLE
Problem with Org-mode headlines

### ISSUE THREAD

**Issue by manuel-uberti** [tarsius/outline-minor-faces#1]
Hi,

thanks for this package. This what I see in an Org file:

![shot](https://user-images.githubusercontent.com/8199224/50373135-7ffff100-05da-11e9-8cc3-af4057b16372.png)

This is how I set up `outline-minor-faces`:

```
(use-package outline-minor-faces        ; Headings faces for outline-minor-mode
  :ensure t
  :after outline
  :config (add-hook 'outline-minor-mode-hook
                    'outline-minor-faces-add-font-lock-keywords))
```
I am using latest [solarized-emacs](https://github.com/bbatsov/solarized-emacs) from MELPA. If you need more info, feel free to ask.

**Comment by tarsius** [comment]
What is wrong in that screenshot?  It appears that `org-bullets` is having some issues.  Is that what you are talking about?

From the screenshot alone I cannot even tell that `outline-minor-faces` is in effect in this buffer.  I do however guess that `backline` is in effect.

Both `outline-minor-faces` and `backline` are only intended for `outline-MINOR-mode`.  The former only makes sense for use with `outline-minor-mode`.  The latter could also be of use `outline-mode` and `org-mode` buffers, but I haven't investigated yet whether some additional work is required to make that work.

Both packages only have an effect in buffers in which `outline-minor-mode` has been enabled.  My guess is that you have enabled that mode in `org-mode`, which is something you shouldn't do.

**Comment by manuel-uberti** [comment]
You're absolutely right, thanks for the explanation. I'll check why `outline-minor-mode` is on, since it shouldn't be.

Consider this close. :)
