### ISSUE TITLE
Allow conditional execution of outline-minor-faces-add-font-lock-keywords

### ISSUE THREAD

**Issue by edgimar** [tarsius/outline-minor-faces#4]
There are some major-modes that I use outline-minor-mode with where I don't want to have outline-minor-faces active.  To work around that, I wrap `outline-minor-faces-add-font-lock-keywords` in a function that conditionally executes it depending on the current major mode.

It would be nice if the outline-minor-faces package provided a list (or predicate) that could be customized to achieve this without the need to manually wrap `outline-minor-faces-add-font-lock-keywords`.

**Comment by tarsius** [comment]
To make `outline-minor-faces-add-font-lock-keywords` only have an effect in certain major-modes you could just add it to the respective mode hooks, instead of on `outline-minor-mode-hook`.

**Comment by edgimar** [comment]
Yes, that's true -- maybe it would be good to add this info to the README?
