### ISSUE TITLE
Ugly outline-minor-1 face with solarized-dark

### ISSUE THREAD

**Issue by funnes** [tarsius/outline-minor-faces#7]
Hi,

I am using [solarized-emacs](https://github.com/bbatsov/solarized-emacs) and for some reason that I can't figure out `outline-minor-1` has a weird background color set:

![image](https://user-images.githubusercontent.com/29305982/116980253-4cfbbb00-acc6-11eb-8888-852b68500b68.png)

solarized-light while also having a different color for the first heading looks much nicer.

Where does this background color come from? Neither `outline-minor-0` nor `outline-1` which `outline-minor-1` inherits from have that color.

**Comment by tarsius** [comment]
Well something(tm) sets that face property. I also use `solarized-light` and this does not happen for me, so that probably isn't responsible.

I don't know what I can do here to help you and don't think my code is responsible, so I am closing this. Try to reproduce without your configuration and additional packages and gradually add things back to narrow down the issue.

**Comment by funnes** [comment]
Yeah you are right. The face is fine with a minimal init.el.

![image](https://user-images.githubusercontent.com/29305982/117031973-653cfb80-ad01-11eb-826a-8c6f90663fc5.png)

Apparently some package that gets loaded after solarized sets that face property so loading the theme later should fix it. Sorry for wasting your time, I thought your package might do some magic to give the top level heading a different background.

Awesome package by the way, makes editing groff much more pleasant.

**Comment by funnes** [comment]
Ok no this is weird. I managed to reproduce this with a minimal init file but it only happens when emacs is started in daemon mode.

`minimal.el`:
```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

(package-install 'solarized-theme)
(package-install 'outline-minor-faces)

(load-theme 'solarized-dark t)

(require 'outline)
(add-hook 'text-mode-hook
          'outline-minor-mode)
(add-hook 'outline-minor-mode-hook
          'outline-minor-faces-add-font-lock-keywords)
```
```
emacs -Q -l minimal.el --daemon
emacsclient --create-frame outline-minor-faces-test.txt
```
![image](https://user-images.githubusercontent.com/29305982/117053981-e56f5b00-ad19-11eb-9a23-1ebcb8572185.png)
```
emacs -Q -l minimal.el outline-minor-faces-test.txt
```
![image](https://user-images.githubusercontent.com/29305982/117054251-32533180-ad1a-11eb-839e-fca755485bac.png)

It also happens with `solarized-light` it's just more subtle:

![image](https://user-images.githubusercontent.com/29305982/117054900-dfc64500-ad1a-11eb-88a8-e97ec5e1828f.png)
 
I have no idea what is going on here, some race condition maybe?

**Comment by tarsius** [comment]
`solarized-light` is supposed to look like this. Here's the code that does that (from `solarized.el`):

```lisp
     `(outline-minor-0 ((,class (:weight bold :background ,s-base2))))
     `(outline-minor-1
       ((,class (:inherit (outline-minor-0 outline-1)
                 :background ,(solarized-color-blend s-base3 yellow .9)))))
```

Apparently that does not work so well for `solarized-dark`.

Maybe it did work well when I themed that 2 1/2 years ago, maybe not. You will have to talk to the `solarized` maintainers about this. Please fix the dark variant without breaking the light variant. You can do that be specifying different values for the `light-class` and the `dark-class`.

While I use `solarized` (light), I locked it at `1.3.1`. After that release some major refactoring follows, which IMO is a dead end and why I stopped contributing to this theme.
